/* Generated By:JavaCC: Do not edit this line. RobotGrammarConstants.java */
package LyM.parserProyecto.analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COLON = 5;
  /** RegularExpression Id. */
  int SEMICOLON = 6;
  /** RegularExpression Id. */
  int COMA = 7;
  /** RegularExpression Id. */
  int ROBOT_R = 8;
  /** RegularExpression Id. */
  int VARS = 9;
  /** RegularExpression Id. */
  int PROCS = 10;
  /** RegularExpression Id. */
  int ASSIGNTO = 11;
  /** RegularExpression Id. */
  int NUMERO = 12;
  /** RegularExpression Id. */
  int CADENA = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"ROBOT_R\"",
    "\"VARS\"",
    "\"PROCS\"",
    "\"assignto\"",
    "<NUMERO>",
    "<CADENA>",
  };

}
