/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ROBOT_R = 5;
  /** RegularExpression Id. */
  int VARS = 6;
  /** RegularExpression Id. */
  int PROCS = 7;
  /** RegularExpression Id. */
  int MOV = 8;
  /** RegularExpression Id. */
  int RIGHT = 9;
  /** RegularExpression Id. */
  int PUT = 10;
  /** RegularExpression Id. */
  int PICK = 11;
  /** RegularExpression Id. */
  int POP = 12;
  /** RegularExpression Id. */
  int GO = 13;
  /** RegularExpression Id. */
  int HOP = 14;
  /** RegularExpression Id. */
  int ASSIGNTO = 15;
  /** RegularExpression Id. */
  int GOTO = 16;
  /** RegularExpression Id. */
  int MOVE = 17;
  /** RegularExpression Id. */
  int TURN = 18;
  /** RegularExpression Id. */
  int BALLOONS = 19;
  /** RegularExpression Id. */
  int CHIPS = 20;
  /** RegularExpression Id. */
  int COMA = 21;
  /** RegularExpression Id. */
  int SEMICOLON = 22;
  /** RegularExpression Id. */
  int NUM = 23;
  /** RegularExpression Id. */
  int DIGIT = 24;
  /** RegularExpression Id. */
  int CADENA = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"ROBOT_R\"",
    "\"VARS\"",
    "\"PROCS\"",
    "\"Mov\"",
    "\"RIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"assignto\"",
    "\"goto\"",
    "\"move\"",
    "\"turn\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "\",\"",
    "\";\"",
    "<NUM>",
    "<DIGIT>",
    "<CADENA>",
    "\"(\"",
    "\")\"",
  };

}
